// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQjv-5Oi5zV4cMIKgRo-P-aOZn2_s4iyY',
    appId: '1:120213722215:web:ea342c8a84f1fa2135f0c2',
    messagingSenderId: '120213722215',
    projectId: 'todo-melih',
    authDomain: 'todo-melih.firebaseapp.com',
    storageBucket: 'todo-melih.appspot.com',
    measurementId: 'G-8WTH6HPPQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8H8lywsexAfANxfH0r-rQLIXycB5cn18',
    appId: '1:120213722215:android:76538c2a8bad7fcb35f0c2',
    messagingSenderId: '120213722215',
    projectId: 'todo-melih',
    storageBucket: 'todo-melih.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwpCa6dtzLTEsB9YaNmFkLh25rs34-KyI',
    appId: '1:120213722215:ios:3b804d6cc5c92f8a35f0c2',
    messagingSenderId: '120213722215',
    projectId: 'todo-melih',
    storageBucket: 'todo-melih.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwpCa6dtzLTEsB9YaNmFkLh25rs34-KyI',
    appId: '1:120213722215:ios:cd5461c87c2aa49035f0c2',
    messagingSenderId: '120213722215',
    projectId: 'todo-melih',
    storageBucket: 'todo-melih.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
